In [1]:
import numpy as np
import pandas as pd

D:\Anaconda\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
match=pd.read_csv('IPL_Matches_2008_2022 (1).csv')
deliveries=pd.read_csv('IPL_Ball_by_Ball_2008_2022.csv')

In [3]:
match.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

In [4]:
deliveries.head()

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam
0,1312200,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
1,1312200,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals
2,1312200,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals
3,1312200,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
4,1312200,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals

In [5]:
total_score_df=deliveries.groupby(['ID','innings']).sum()['total_run'].reset_index()

In [6]:
total_score_df

           ID  innings  total_run
0      335982        1        222
1      335982        2         82
2      335983        1        240
3      335983        2        207
4      335984        1        129
...       ...      ...        ...
1923  1312198        2        193
1924  1312199        1        157
1925  1312199        2        161
1926  1312200        1        130
1927  1312200        2        133

[1928 rows x 3 columns]

In [7]:
total_score_df=total_score_df[total_score_df['innings']==1]

In [8]:
match_df=match.merge(total_score_df[['ID','total_run']],left_on='ID',right_on='ID')

In [9]:
match_df.shape

(950, 21)

In [10]:
match_df['Team1'].unique()

array(['Rajasthan Royals', 'Royal Challengers Bangalore',
       'Sunrisers Hyderabad', 'Delhi Capitals', 'Chennai Super Kings',
       'Gujarat Titans', 'Lucknow Super Giants', 'Kolkata Knight Riders',
       'Punjab Kings', 'Mumbai Indians', 'Kings XI Punjab',
       'Delhi Daredevils', 'Rising Pune Supergiant', 'Gujarat Lions',
       'Rising Pune Supergiants', 'Pune Warriors', 'Deccan Chargers',
       'Kochi Tuskers Kerala'], dtype=object)

In [11]:
teams=[
    'Rajasthan Royals', 
    'Royal Challengers Bangalore',
    'Sunrisers Hyderabad', 
    'Delhi Capitals', 
    'Chennai Super Kings',
    'Gujarat Titans', 
    'Lucknow Super Giants', 
    'Kolkata Knight Riders',
    'Mumbai Indians',
    'Kings XI Punjab',
]

In [12]:
match_df['Team1']=match_df['Team1'].str.replace('Delhi Daredevils','Delhi Capitals')
match_df['Team2']=match_df['Team2'].str.replace('Delhi Daredevils','Delhi Capitals')

match_df['Team1']=match_df['Team1'].str.replace('Deccan Chargers','Sunrisers Hyderabad')
match_df['Team2']=match_df['Team2'].str.replace('Deccan Chargers','Sunrisers Hyderabad')

match_df['Team1']=match_df['Team1'].str.replace('Punjab Kings','Kings XI Punjab')
match_df['Team2']=match_df['Team2'].str.replace('Punjab Kings','Kings XI Punjab')

In [13]:
match_df=match_df[match_df['Team1'].isin(teams)]
match_df=match_df[match_df['Team2'].isin(teams)]

In [14]:
match_df.shape

(835, 21)

In [15]:
match_df.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,...,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2,total_run
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon,130
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,...,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon,157
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,...,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough,207
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,...,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma,188
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Kings XI Punjab,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,...,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan,157

In [16]:
match_df=match_df[['ID','City','WinningTeam','total_run','Team1','Team2']]

In [17]:
delivery_df=match_df.merge(deliveries,on='ID')

In [18]:
second_inning=delivery_df[delivery_df['innings']==2]

In [19]:
second_inning.shape

(95974, 22)

In [20]:
#finction to determine boaling team
def determine_boling_team(row):
    if row['BattingTeam']==row['Team1']:
        return row['Team2']
    else:
        return row['Team1']

second_inning['BoalingTeam']=second_inning.apply(determine_boling_team, axis=1)

C:\Users\TCS\AppData\Local\Temp\ipykernel_17156\3174840301.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  second_inning['BoalingTeam']=second_inning.apply(determine_boling_team, axis=1)

In [21]:
second_inning.head()

,ID,City,WinningTeam,total_run_x,Team1,Team2,innings,overs,ballnumber,batter,...,batsman_run,extras_run,total_run_y,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BoalingTeam
120,1312200,Ahmedabad,Gujarat Titans,130,Rajasthan Royals,Gujarat Titans,2,0,1,WP Saha,...,0,0,0,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals
121,1312200,Ahmedabad,Gujarat Titans,130,Rajasthan Royals,Gujarat Titans,2,0,2,WP Saha,...,0,0,0,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals
122,1312200,Ahmedabad,Gujarat Titans,130,Rajasthan Royals,Gujarat Titans,2,0,3,WP Saha,...,1,0,1,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals
123,1312200,Ahmedabad,Gujarat Titans,130,Rajasthan Royals,Gujarat Titans,2,0,4,Shubman Gill,...,0,0,0,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals
124,1312200,Ahmedabad,Gujarat Titans,130,Rajasthan Royals,Gujarat Titans,2,0,5,Shubman Gill,...,0,0,0,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals

In [22]:
print(second_inning['total_run_y'].dtype)

int64

In [23]:
# second_inning['total_run_y'] = pd.to_numeric(second_inning['total_run_y'], errors='coerce')

second_inning['current_score']=second_inning.groupby('ID')['total_run_y'].cumsum()

C:\Users\TCS\AppData\Local\Temp\ipykernel_17156\1413174206.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  second_inning['current_score']=second_inning.groupby('ID')['total_run_y'].cumsum()

In [24]:
second_inning['runs_left']=second_inning['total_run_x']-second_inning['current_score']

C:\Users\TCS\AppData\Local\Temp\ipykernel_17156\4144678214.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  second_inning['runs_left']=second_inning['total_run_x']-second_inning['current_score']

In [25]:
second_inning

,ID,City,WinningTeam,total_run_x,Team1,Team2,innings,overs,ballnumber,batter,...,total_run_y,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BoalingTeam,current_score,runs_left
120,1312200,Ahmedabad,Gujarat Titans,130,Rajasthan Royals,Gujarat Titans,2,0,1,WP Saha,...,0,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals,0,130
121,1312200,Ahmedabad,Gujarat Titans,130,Rajasthan Royals,Gujarat Titans,2,0,2,WP Saha,...,0,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals,0,130
122,1312200,Ahmedabad,Gujarat Titans,130,Rajasthan Royals,Gujarat Titans,2,0,3,WP Saha,...,1,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals,1,129
123,1312200,Ahmedabad,Gujarat Titans,130,Rajasthan Royals,Gujarat Titans,2,0,4,Shubman Gill,...,0,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals,1,129
124,1312200,Ahmedabad,Gujarat Titans,130,Rajasthan Royals,Gujarat Titans,2,0,5,Shubman Gill,...,0,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals,1,129
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198930,335982,Bangalore,Kolkata Knight Riders,222,Royal Challengers Bangalore,Kolkata Knight Riders,2,14,5,P Kumar,...,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,80,142
198931,335982,Bangalore,Kolkata Knight Riders,222,Royal Challengers Bangalore,Kolkata Knight Riders,2,14,6,SB Joshi,...,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,81,141
198932,335982,Bangalore,Kolkata Knight Riders,222,Royal Challengers Bangalore,Kolkata Knight Riders,2,14,7,P Kumar,...,0,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,81,141
198933,335982,Bangalore,Kolkata Knight Riders,222,Royal Challengers Bangalore,Kolkata Knight Riders,2,15,1,SB Joshi,...,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,82,140
198934,335982,Bangalore,Kolkata Knight Riders,222,Royal Challengers Bangalore,Kolkata Knight Riders,2,15,2,SB Joshi,...,0,0,1,SB Joshi,caught,BB McCullum,Royal Challengers Bangalore,Kolkata Knight Riders,82,140

In [26]:
second_inning['balls_left']=120-(second_inning['overs']*6+second_inning['ballnumber'])

C:\Users\TCS\AppData\Local\Temp\ipykernel_17156\1333658983.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  second_inning['balls_left']=120-(second_inning['overs']*6+second_inning['ballnumber'])

In [27]:
second_inning.tail()

,ID,City,WinningTeam,total_run_x,Team1,Team2,innings,overs,ballnumber,batter,...,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BoalingTeam,current_score,runs_left,balls_left
198930,335982,Bangalore,Kolkata Knight Riders,222,Royal Challengers Bangalore,Kolkata Knight Riders,2,14,5,P Kumar,...,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,80,142,31
198931,335982,Bangalore,Kolkata Knight Riders,222,Royal Challengers Bangalore,Kolkata Knight Riders,2,14,6,SB Joshi,...,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,81,141,30
198932,335982,Bangalore,Kolkata Knight Riders,222,Royal Challengers Bangalore,Kolkata Knight Riders,2,14,7,P Kumar,...,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,81,141,29
198933,335982,Bangalore,Kolkata Knight Riders,222,Royal Challengers Bangalore,Kolkata Knight Riders,2,15,1,SB Joshi,...,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,82,140,29
198934,335982,Bangalore,Kolkata Knight Riders,222,Royal Challengers Bangalore,Kolkata Knight Riders,2,15,2,SB Joshi,...,0,1,SB Joshi,caught,BB McCullum,Royal Challengers Bangalore,Kolkata Knight Riders,82,140,28

In [28]:
second_inning['player_out']=second_inning['player_out'].fillna('0')
second_inning['player_out']=second_inning['player_out'].apply(lambda x:x if x=='0' else '1')
second_inning['player_out']=second_inning['player_out'].astype('int')
wickets=second_inning.groupby('ID')['player_out'].cumsum().values
second_inning['wickets_left']=10-wickets

C:\Users\TCS\AppData\Local\Temp\ipykernel_17156\811177444.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  second_inning['player_out']=second_inning['player_out'].fillna('0')
C:\Users\TCS\AppData\Local\Temp\ipykernel_17156\811177444.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  second_inning['player_out']=second_inning['player_out'].apply(lambda x:x if x=='0' else '1')
C:\Users\TCS\AppData\Local\Temp\ipykernel_17156\811177444.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  second_inning['player_out']=second_inning['player_out'].astype('int')
C:\Users\TCS\AppData\Local\Temp\ipykernel_17156\811177444.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  second_inning['wickets_left']=10-wickets

In [29]:
second_inning['crr']=second_inning['current_score']/((120-second_inning['balls_left'])/6)

C:\Users\TCS\AppData\Local\Temp\ipykernel_17156\2787345912.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  second_inning['crr']=second_inning['current_score']/((120-second_inning['balls_left'])/6)

In [30]:
second_inning['rrr']=(second_inning['runs_left']*6)/second_inning["balls_left"]

C:\Users\TCS\AppData\Local\Temp\ipykernel_17156\1159216146.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  second_inning['rrr']=(second_inning['runs_left']*6)/second_inning["balls_left"]

In [31]:
def result(row):
    if row['BattingTeam']==row["WinningTeam"]:
        return 1
    else:
        return 0

second_inning['result']=second_inning.apply(result,axis=1)

C:\Users\TCS\AppData\Local\Temp\ipykernel_17156\1212331871.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  second_inning['result']=second_inning.apply(result,axis=1)

In [32]:
second_inning.head()

,ID,City,WinningTeam,total_run_x,Team1,Team2,innings,overs,ballnumber,batter,...,fielders_involved,BattingTeam,BoalingTeam,current_score,runs_left,balls_left,wickets_left,crr,rrr,result
120,1312200,Ahmedabad,Gujarat Titans,130,Rajasthan Royals,Gujarat Titans,2,0,1,WP Saha,...,NaN,Gujarat Titans,Rajasthan Royals,0,130,119,10,0.0,6.554622,1
121,1312200,Ahmedabad,Gujarat Titans,130,Rajasthan Royals,Gujarat Titans,2,0,2,WP Saha,...,NaN,Gujarat Titans,Rajasthan Royals,0,130,118,10,0.0,6.610169,1
122,1312200,Ahmedabad,Gujarat Titans,130,Rajasthan Royals,Gujarat Titans,2,0,3,WP Saha,...,NaN,Gujarat Titans,Rajasthan Royals,1,129,117,10,2.0,6.615385,1
123,1312200,Ahmedabad,Gujarat Titans,130,Rajasthan Royals,Gujarat Titans,2,0,4,Shubman Gill,...,NaN,Gujarat Titans,Rajasthan Royals,1,129,116,10,1.5,6.672414,1
124,1312200,Ahmedabad,Gujarat Titans,130,Rajasthan Royals,Gujarat Titans,2,0,5,Shubman Gill,...,NaN,Gujarat Titans,Rajasthan Royals,1,129,115,10,1.2,6.730435,1

In [33]:
final_df=second_inning[['BattingTeam','BoalingTeam','City','runs_left','balls_left','wickets_left','total_run_x','crr','rrr','result']]

In [34]:
final_df=final_df.sample(final_df.shape[0])

In [35]:
final_df.sample()

,BattingTeam,BoalingTeam,City,runs_left,balls_left,wickets_left,total_run_x,crr,rrr,result
69311,Mumbai Indians,Chennai Super Kings,Pune,41,24,9,169,8.0,10.25,1

In [36]:
final_df.dropna(inplace=True)

In [37]:
final_df=final_df[final_df['balls_left']!=0]

In [38]:
x=final_df.iloc[:,:-1]
y=final_df.iloc[:,-1]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [39]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

trf=ColumnTransformer([
    ('trf',OneHotEncoder(drop='first'),['BattingTeam','BoalingTeam','City'])
]
    ,remainder='passthrough')

In [40]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

In [41]:
pipe=Pipeline([
    ('step1',trf),
    ('step2',LogisticRegression(solver='liblinear'))
])

In [42]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trf',
                                                  OneHotEncoder(drop='first'),
                                                  ['BattingTeam', 'BoalingTeam',
                                                   'City'])])),
                ('step2', LogisticRegression(solver='liblinear'))])

In [43]:
y_pred=pipe.predict(x_test)

In [44]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8155913678692912

In [45]:
teams

['Rajasthan Royals',
 'Royal Challengers Bangalore',
 'Sunrisers Hyderabad',
 'Delhi Capitals',
 'Chennai Super Kings',
 'Gujarat Titans',
 'Lucknow Super Giants',
 'Kolkata Knight Riders',
 'Mumbai Indians',
 'Kings XI Punjab']

In [46]:
final_df['City'].unique()

array(['Kolkata', 'Dharamsala', 'Delhi', 'Abu Dhabi', 'Bangalore',
       'Chandigarh', 'Chennai', 'Mumbai', 'Bengaluru', 'Pune',
       'Hyderabad', 'Dubai', 'Jaipur', 'Centurion', 'Johannesburg',
       'Ahmedabad', 'Kimberley', 'Visakhapatnam', 'Cape Town', 'Ranchi',
       'Raipur', 'Nagpur', 'Durban', 'Indore', 'Cuttack', 'Sharjah',
       'Navi Mumbai', 'Port Elizabeth', 'East London', 'Bloemfontein'],
      dtype=object)

In [48]:
import pickle
pickle.dump(pipe,open('pipe.pkl','wb'))

NameError: name 'final_df' is not defined